import { helpRow } from "@/lib/keymap/help-row";
import type { HelpRow, KeymapDef } from "@/lib/keymap/types";

export const CALENDAR_KEYMAPS: KeymapDef[] = [
  {
    id: "calendar.focus_prev_day",
    key: "h",
    triggerKey: "h",
    section: "calendar",
    label: "Focus previous day",
  },
  {
    id: "calendar.focus_next_day",
    key: "l",
    triggerKey: "l",
    section: "calendar",
    label: "Focus next day",
  },
  {
    id: "calendar.focus_prev_week",
    key: "k",
    triggerKey: "k",
    section: "calendar",
    label: "Focus previous week",
  },
  {
    id: "calendar.focus_next_week",
    key: "j",
    triggerKey: "j",
    section: "calendar",
    label: "Focus next week",
  },
  {
    id: "calendar.prev_period",
    key: "[",
    triggerKey: "[",
    section: "calendar",
    label: "Previous period",
  },
  {
    id: "calendar.next_period",
    key: "]",
    triggerKey: "]",
    section: "calendar",
    label: "Next period",
  },
  {
    id: "calendar.scroll_top",
    key: "gg",
    triggerKey: "g",
    section: "calendar",
    label: "First hour (00:00)",
  },
  {
    id: "calendar.scroll_bottom",
    key: "G",
    triggerKey: "G",
    section: "calendar",
    label: "Last hour (23:00)",
  },
  {
    id: "calendar.scroll_down_hour",
    key: "e",
    triggerKey: "e",
    modifiers: ["ctrl"],
    section: "calendar",
    label: "Scroll down 1 hour",
  },
  {
    id: "calendar.scroll_up_hour",
    key: "y",
    triggerKey: "y",
    modifiers: ["ctrl"],
    section: "calendar",
    label: "Scroll up 1 hour",
  },
  {
    id: "calendar.half_page_down",
    key: "d",
    triggerKey: "d",
    modifiers: ["ctrl"],
    section: "calendar",
    label: "Scroll half page down",
  },
  {
    id: "calendar.half_page_up",
    key: "u",
    triggerKey: "u",
    modifiers: ["ctrl"],
    section: "calendar",
    label: "Scroll half page up",
  },
  {
    id: "calendar.day_view",
    key: "d",
    triggerKey: "d",
    section: "calendar",
    label: "Day view",
  },
  {
    id: "calendar.week_view",
    key: "w",
    triggerKey: "w",
    section: "calendar",
    label: "Week view",
  },
  {
    id: "calendar.month_view",
    key: "m",
    triggerKey: "m",
    section: "calendar",
    label: "Month view",
  },
  {
    id: "calendar.today",
    key: "t",
    triggerKey: "t",
    section: "calendar",
    label: "Jump to today",
  },
  {
    id: "calendar.toggle_allday",
    key: "a",
    triggerKey: "a",
    section: "calendar",
    label: "Toggle all-day bar",
  },
  {
    id: "calendar.actions",
    key: "ga",
    triggerKey: "a",
    section: "calendar",
    label: "Calendar management",
  },
];

export const CALENDAR_HELP_ROWS: HelpRow[] = [
  helpRow(
    ["calendar.focus_prev_day", "calendar.focus_next_day"],
    "h / l",
    "Focus previous / next day",
  ),
  helpRow(
    ["calendar.focus_prev_week", "calendar.focus_next_week"],
    "k / j",
    "Focus previous / next week",
  ),
  helpRow(
    ["calendar.prev_period", "calendar.next_period"],
    "[ / ]",
    "Previous / next visible period",
  ),
  helpRow("calendar.scroll_top", "gg", "First hour (00:00)"),
  helpRow("calendar.scroll_bottom", "G", "Last hour (23:00)"),
  helpRow("calendar.scroll_down_hour", "<C-e>", "Scroll down 1 hour"),
  helpRow("calendar.scroll_up_hour", "<C-y>", "Scroll up 1 hour"),
  helpRow("calendar.half_page_down", "<C-d>", "Scroll half page down"),
  helpRow("calendar.half_page_up", "<C-u>", "Scroll half page up"),
  helpRow(
    ["calendar.day_view", "calendar.week_view", "calendar.month_view"],
    "d / w / m",
    "Day / week / month view",
  ),
  helpRow("calendar.today", "t", "Jump to today"),
  helpRow("calendar.toggle_allday", "a", "Toggle all-day bar"),
  helpRow("calendar.actions", "ga", "Calendar management"),
];
