import { helpRow } from "@/lib/keymap/help-row";
import type { HelpRow, KeymapDef } from "@/lib/keymap/types";

export const KANBAN_KEYMAPS: KeymapDef[] = [
  {
    id: "kanban.col_left",
    key: "h",
    triggerKey: "h",
    section: "kanban",
    label: "Move between columns",
  },
  {
    id: "kanban.col_right",
    key: "l",
    triggerKey: "l",
    section: "kanban",
    label: "Move between columns",
  },
  {
    id: "kanban.row_down",
    key: "j",
    triggerKey: "j",
    section: "kanban",
    label: "Move within column",
  },
  {
    id: "kanban.row_up",
    key: "k",
    triggerKey: "k",
    section: "kanban",
    label: "Move within column",
  },
  {
    id: "kanban.move_task_left",
    key: "H",
    triggerKey: "H",
    section: "kanban",
    label: "Move task left",
  },
  {
    id: "kanban.move_task_right",
    key: "L",
    triggerKey: "L",
    section: "kanban",
    label: "Move task right",
  },
  {
    id: "kanban.swap_col_left",
    key: "<",
    triggerKey: "<",
    section: "kanban",
    label: "Swap column left",
  },
  {
    id: "kanban.swap_col_right",
    key: ">",
    triggerKey: ">",
    section: "kanban",
    label: "Swap column right",
  },
  {
    id: "kanban.jump_waiting",
    key: "W",
    triggerKey: "W",
    section: "kanban",
    label: "Jump to Waiting column",
  },
  {
    id: "kanban.jump_in_progress",
    key: "I",
    triggerKey: "I",
    section: "kanban",
    label: "Jump to In Progress column",
  },
  {
    id: "kanban.jump_blocked",
    key: "B",
    triggerKey: "B",
    section: "kanban",
    label: "Jump to Blocked column",
  },
  {
    id: "kanban.jump_done",
    key: "X",
    triggerKey: "X",
    section: "kanban",
    label: "Jump to Done column",
  },
  {
    id: "kanban.set_waiting",
    key: "w",
    triggerKey: "w",
    section: "kanban",
    label: "Set status Waiting",
  },
  {
    id: "kanban.set_in_progress",
    key: "i",
    triggerKey: "i",
    section: "kanban",
    label: "Set status In Progress",
  },
  {
    id: "kanban.set_blocked",
    key: "b",
    triggerKey: "b",
    section: "kanban",
    label: "Set status Blocked",
  },
  {
    id: "kanban.complete",
    key: "x",
    triggerKey: "x",
    section: "kanban",
    label: "Complete task",
  },
  {
    id: "kanban.search",
    key: "/",
    triggerKey: "/",
    section: "kanban",
    label: "Search filter",
  },
  {
    id: "kanban.edit",
    key: "e",
    triggerKey: "e",
    section: "kanban",
    label: "Edit / create task",
  },
  {
    id: "kanban.toggle_select",
    key: "v",
    triggerKey: "v",
    section: "kanban",
    label: "Toggle select",
  },
  {
    id: "kanban.visual_mode",
    key: "V",
    triggerKey: "V",
    section: "kanban",
    label: "Visual select mode",
  },
  {
    id: "kanban.delete",
    key: "dd",
    triggerKey: "d",
    section: "kanban",
    label: "Delete task",
  },
  {
    id: "kanban.escape",
    key: "Escape",
    triggerKey: "Escape",
    section: "kanban",
    label: "Deactivate keyboard",
  },
];

export const KANBAN_HELP_ROWS: HelpRow[] = [
  helpRow(
    ["kanban.col_left", "kanban.col_right"],
    "h / l",
    "Move between columns",
  ),
  helpRow(["kanban.row_down", "kanban.row_up"], "j / k", "Move within column"),
  helpRow(
    ["kanban.move_task_left", "kanban.move_task_right"],
    "H / L",
    "Move task left / right",
  ),
  helpRow(
    ["kanban.swap_col_left", "kanban.swap_col_right"],
    "< / >",
    "Swap column left / right",
  ),
  helpRow(
    [
      "kanban.jump_waiting",
      "kanban.jump_in_progress",
      "kanban.jump_blocked",
      "kanban.jump_done",
    ],
    "W / I / B / X",
    "Jump to column",
  ),
  helpRow(
    [
      "kanban.set_waiting",
      "kanban.set_in_progress",
      "kanban.set_blocked",
      "kanban.complete",
    ],
    "w / i / b / x",
    "Set status / complete",
  ),
  helpRow("kanban.search", "/", "Search filter"),
  helpRow("kanban.edit", "e", "Edit / create task"),
  helpRow(
    ["kanban.toggle_select", "kanban.visual_mode"],
    "v / V",
    "Toggle / visual select",
  ),
  helpRow("kanban.delete", "dd", "Delete task"),
  helpRow("kanban.escape", "<Esc>", "Deactivate keyboard"),
];
