import { helpRow } from "@/lib/keymap/help-row";
import type { HelpRow, KeymapDef } from "@/lib/keymap/types";

export const QUEUE_KEYMAPS: KeymapDef[] = [
  {
    id: "queue.move_down",
    key: "j",
    triggerKey: "j",
    section: "queue",
    label: "Move down",
  },
  {
    id: "queue.move_up",
    key: "k",
    triggerKey: "k",
    section: "queue",
    label: "Move up",
  },
  {
    id: "queue.jump_top",
    key: "gg",
    triggerKey: "g",
    section: "queue",
    label: "Jump to top",
  },
  {
    id: "queue.jump_bottom",
    key: "G",
    triggerKey: "G",
    section: "queue",
    label: "Jump to bottom",
  },
  {
    id: "queue.half_page_down",
    key: "d",
    triggerKey: "d",
    modifiers: ["ctrl"],
    section: "queue",
    label: "Half page down",
  },
  {
    id: "queue.half_page_up",
    key: "u",
    triggerKey: "u",
    modifiers: ["ctrl"],
    section: "queue",
    label: "Half page up",
  },
  {
    id: "queue.search",
    key: "/",
    triggerKey: "/",
    section: "queue",
    label: "Search filter",
  },
  {
    id: "queue.edit",
    key: "e",
    triggerKey: "e",
    section: "queue",
    label: "Edit / create task",
  },
  {
    id: "queue.complete",
    key: "xx / xj / xk",
    triggerKey: "x",
    section: "queue",
    label: "Complete task(s)",
  },
  {
    id: "queue.delete",
    key: "dd / dj / dk",
    triggerKey: "d",
    section: "queue",
    label: "Delete task(s)",
  },
  {
    id: "queue.set_pending",
    key: "pp / pj / pk",
    triggerKey: "p",
    section: "queue",
    label: "Set pending",
  },
  {
    id: "queue.set_wip",
    key: "ww / wj / wk",
    triggerKey: "w",
    section: "queue",
    label: "Set wip",
  },
  {
    id: "queue.set_blocked",
    key: "bb / bj / bk",
    triggerKey: "b",
    section: "queue",
    label: "Set blocked",
  },
  {
    id: "queue.toggle_select",
    key: "v",
    triggerKey: "v",
    section: "queue",
    label: "Toggle select",
  },
  {
    id: "queue.visual_mode",
    key: "V",
    triggerKey: "V",
    section: "queue",
    label: "Visual select mode",
  },
  {
    id: "queue.escape",
    key: "Escape",
    triggerKey: "Escape",
    section: "queue",
    label: "Clear / close",
  },
];

export const QUEUE_HELP_ROWS: HelpRow[] = [
  helpRow(["queue.move_down", "queue.move_up"], "j / k", "Move down / up"),
  helpRow("queue.jump_top", "gg", "Jump to top"),
  helpRow("queue.jump_bottom", "G", "Jump to bottom"),
  helpRow("queue.half_page_down", "<C-d>", "Half page down"),
  helpRow("queue.half_page_up", "<C-u>", "Half page up"),
  helpRow("queue.search", "/", "Search filter"),
  helpRow("queue.edit", "e", "Edit / create task"),
  helpRow("queue.complete", "xx / xj / xk", "Complete task(s)"),
  helpRow("queue.delete", "dd / dj / dk", "Delete task(s)"),
  helpRow("queue.set_pending", "pp / pj / pk", "Set pending"),
  helpRow("queue.set_wip", "ww / wj / wk", "Set wip"),
  helpRow("queue.set_blocked", "bb / bj / bk", "Set blocked"),
  helpRow("queue.toggle_select", "v", "Toggle select"),
  helpRow("queue.visual_mode", "V", "Visual select mode"),
  helpRow("queue.escape", "<Esc>", "Clear / close"),
];
